- hosts: jenkins_master
  sudo: yes
  vars:
    jenkins_hostname: jenkins.fastfeedback.rocks
    java_packages: java-1.8.0-openjdk-devel
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      become: true
  
